apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::012558148778:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12VS89A3PUZRE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::012558148778:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T13:33:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1637"
  uid: f97f7795-315b-48d5-b553-02c9614ad04b
